[project]
name = "nicar-2026-polars"
version = "0.1.0"
description = "A Python project for demonstrating how to use Polars to analyze election data."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.10.0",
    "jupyterlab>=4.5.3",
    "polars>=1.38.1",
]
